version: '3'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass '123456'
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
